### ISSUE TITLE
E_COMPILE_ERROR

### ISSUE THREAD

**Issue by teracube** [kenygamer/iProtector-v4.0#3]
Hi,

Crash when server started with e compile error

Server KO refuse to start  with this last version plugins
&6947 https://poggit.pmmp.io/r/10077/iProtector.phar
&6944 https://poggit.pmmp.io/r/10074/iProtector.phar

But OK all is fine  with 
&6937 https://poggit.pmmp.io/r/10061/iProtector.phar

PMMP version : PocketMine-MP 1.6.2dev-380
https://jenkins.pmmp.io/job/PocketMine-MP/lastSuccessfulBuild/artifact/PocketMine-MP_1.6.2dev-380_0c798222_API-3.0.0-ALPHA7.phar

CrashDump 
PocketMine-MP Crash Dump Sun Aug 13 10:07:07 CEST 2017

Error: Declaration of kenygamer\iProtector\Main::onCommand(pocketmine\command\CommandSender $sender, pocketmine\command\Command $cmd, $label, array $args) must be compatible with pocketmine\command\CommandExecutor::onCommand(pocketmine\command\CommandSender $sender, pocketmine\command\Command $command, string $label, array $args): bool
File: iProtector.phar/src/kenygamer/iProtector/Main
Line: 32
Type: E_COMPILE_ERROR

THIS CRASH WAS CAUSED BY A PLUGIN

Code:
[23] use pocketmine\Player;
[24] use pocketmine\plugin\PluginBase;
[25] use pocketmine\utils\TextFormat;
[26] use pocketmine\event\entity\EntityDamageEvent;
[27] use pocketmine\event\entity\EntityExplodeEvent;
[28] use pocketmine\event\player\PlayerInteractEvent;
[29] use pocketmine\event\block\BlockPlaceEvent;
[30] use pocketmine\event\block\BlockBreakEvent;
[31] 
[32] class Main extends PluginBase implements Listener
[33] {
[34]     /** @var array */
[35]     protected $c;
[36]     /** Command prefix */
[37]     const PREFIX = TextFormat::GREEN . "[" . "iProtector" . ":kenygamer" . "]" . TextFormat::RESET . " ";
[38]     
[39]     /**
[40]      * onEnable()
[41]      *
[42]      * Plugin enable

Backtrace:

PocketMine-MP version: 1.6.2dev #380 [Protocol 113; API 3.0.0-ALPHA7]
Git commit: 0c798222a4af61fd5dac719466469dd336453466
uname -a: Linux ns3023271.ip-151-80-230.eu 4.4.19-mod-std-ipv6-64 #1 SMP Mon Aug 22 13:05:01 CEST 2016 x86_64
PHP Version: 7.0.17
Zend version: 3.0.0
OS : Linux, linux

Loaded plugins:
PurePerms 1.4.1-dev2 by 64FF00 & ProjectInfinity for API(s) 3.0.0-ALPHA7
BlockPets 1.1.0 by BlockHorizons for API(s) 3.0.0-ALPHA7
AllSigns 1.0.2 by  for API(s) 3.0.0-ALPHA7
ItemCasePE 1.1.0-dev1 by aliuly for API(s) 3.0.0-ALPHA7
FactionsPro 1.4.4-dev2 by Tethered_, HostingItAll.com for API(s) 3.0.0-ALPHA7
xyz 1.0.3 by unerds for API(s) 3.0.0-ALPHA7
EconomyAPI 5.7.1-dev2 by onebone for API(s) 3.0.0-ALPHA7
CrateKeys 1.0.0 by  for API(s) 3.0.0-ALPHA5, 3.0.0-ALPHA6, 3.0.0-ALPHA7
AlwaysSpawn 2.2.3-dev1 by Philip Shilling for API(s) 3.0.0-ALPHA7
KillMoney 1.1.2 by kenygamer for API(s) 3.0.0, 3.0.0-ALPHA1, 3.0.0-ALPHA2, 3.0.0-ALPHA3, 3.0.0-ALPHA4, 3.0.0-ALPHA5, 3.0.0-ALPHA6, 3.0.0-ALPHA7
Jail 1.2.0 by hoyinm14mc for API(s) 2.0.0, 3.0.0-ALPHA3, 3.0.0-ALPHA4, 3.0.0-ALPHA5, 3.0.0-ALPHA6, 3.0.0-ALPHA7
SimpleAuth 2.0.0-alpha7 by PocketMine Team, shoghicp, awzaw for API(s) 3.0.0-ALPHA7
SimpleAuthHelper 2.0.5-dev1 by aliuly for API(s) 3.0.0-ALPHA7
Slapper 1.3.5 by jojoe77777 for API(s) 3.0.0-ALPHA7
PiggyCustomEnchants 1.0.2 by DaPigGuy for API(s) 3.0.0-ALPHA7
essentialsTP 1.2.0-dev1 by  for API(s) 3.0.0-ALPHA7
ChatToDiscord 1.1.0 by eDroid for API(s) 3.0.0, 3.0.0-ALPHA6, 3.0.0-ALPHA7
 

Thanks

**Comment by kenygamer** [comment]
@teracube,
Please delete your iProtector installation and follow the *README.md* steps.

**Comment by teracube** [comment]
I did exactly what you said.
same crash dump with latest version 
PocketMine-MP Crash Dump Sun Aug 13 19:19:35 CEST 2017
Error: Declaration of kenygamer\iProtector\Main::onCommand(pocketmine\command\CommandSender $sender, pocketmine\command\Command $cmd, $label, array $args) must be compatible with pocketmine\command\CommandExecutor::onCommand(pocketmine\command\CommandSender $sender, pocketmine\command\Command $command, string $label, array $args): bool
File: iProtector_v4.0.1#3.1b.phar/src/kenygamer/iProtector/Main
Line: 32
Type: E_COMPILE_ERROR
THIS CRASH WAS CAUSED BY A PLUGIN

but no problem with this version : https://poggit.pmmp.io/r/10061/iProtector.phar

thanks

**Comment by kenygamer** [comment]
@teracube Hmm. Please repeat all download steps again.
I think the last commit should fix the issue

**Comment by teracube** [comment]
it's ok
thanks kenygamer

**Comment by TheFixerDevelopment** [comment]
The reason upon this, is because the developer of this plugin hasn't made it ALPHA7 compatibilitie. If he has, then he's done it wrong. Or the coding onCommand is incorrect, however, try the steps again, as he might've fixed the issue. If not, then the developer still needs to make Alpha7 compatible (FULLY.) as it specifically warns you that Plugins could break with ALPHA7 version. If none of his steps didn't work, then please try downgrading to ALPHA 6. As this plugin works fine on my server, and is on ALPHA6.

**Comment by TheFixerDevelopment** [comment]
If However this issue is solved, please close this issue. Thank you.

**Comment by kenygamer** [comment]
@teracube Did it work?

**Comment by teracube** [comment]
hi kenygamer
i was on holiday ;-)
thanks you very much 
working fine

**Comment by kenygamer** [comment]
@teracube very good no problem, closing.
