### ISSUE TITLE
Add Item Frame Protection

### ISSUE THREAD

**Issue by mote166** [kenygamer/iProtector-v4.0#4]
Add protection to items in item frame so once touch is set to true no one can flip or remove the items in itemframes

**Comment by mote166** [comment]
Dude if u haven't noticed , i really need this plugin for the pictures plugin i have , it stores maps in item frame but the players keep breaking it

**Comment by kenygamer** [comment]
@mote166 I'm working on it

**Comment by kenygamer** [comment]
@mote166,
I'm going to start working with your feature request probably tomorrow or the day after tomorrow.

**Comment by mote166** [comment]
K thanks .

**Comment by kenygamer** [comment]
@mote166 
I'm afraid your feature request will delay. Although I replied because I started to rewrite my iProtector fork, it was just to give you peace of mind. Please note that this may take time. However, I already know how to do what you are looking for, but you should give me time to finish with this first.

**Comment by mote166** [comment]
K but just try to do it quickly. Thanks

**Comment by kenygamer** [comment]
@mote166 It's 5:17 AM here and I'm still working.

**Comment by kenygamer** [comment]
@mote166 I added your feature request and should be working. I just tried it. You will have to go to the new repository to download it. It's not a stable version at the moment and I'm still re-writing. I'm planning on adding more features.
[**Commit**](https://github.com/kenygamer/pmmp-plugins/commit/add36d30fdced31c81d54e25bf7728550682b52a#diff-87743f18c3db3fefe23a652630511bc9)

**Comment by mote166** [comment]
Can u add that here ? If u added that here which version would work smoother and more stable than the other? The pmmp one or this one ? And what are the bugs with the pmmp one ? Cuz its a protection plugin and i must know what the bugs are .

**Comment by kenygamer** [comment]
@mote166 Please, be patient. The new repository will be released to the public as soon as the API 3.0.0-ALPHA7 is available. I still have to complete a testing phase and work on some extra pair of plugins to add.

All changes will have positive goals to provide a better experience and support.

**Comment by kenygamer** [comment]
@mote166 
https://github.com/kenygamer/pmmp-plugins

**Comment by mote166** [comment]
The server crashed when i installed the plugin from the link above ^ 

Crashdumb:
```
GenisysPro Crash Dump Wed Sep 6 05:52:17 CDT 2017

Error: Declaration of kenygamer\iProtector\Main::onCommand(pocketmine\command\CommandSender $sender, pocketmine\command\Command $command, string $label, array $args): bool must be compatible with pocketmine\command\CommandExecutor::onCommand(pocketmine\command\CommandSender $sender, pocketmine\command\Command $command, $label, array $args)
File: /plugins/iProtector-v4.0-master/src/kenygamer/iProtector/Main
Line: 34
Type: E_COMPILE_ERROR

THIS CRASH WAS CAUSED BY A PLUGIN

Code:
[25] use pocketmine\event\Listener;
[26] use pocketmine\event\server\DataPacketReceiveEvent;
[27] use pocketmine\level\{Level, Position};
[28] use pocketmine\math\Vector3;
[29] use pocketmine\network\protocol\ItemFrameDropItemPacket;
[30] use pocketmine\Player;
[31] use pocketmine\plugin\PluginBase;
[32] use pocketmine\utils\TextFormat as TF;
[33] 
[34] class Main extends PluginBase implements Listener{
[35]   
[36]   /** Plugin name */
[37]   const PLUGIN_NAME = "iProtector-v4.0";
[38]   /** Plugin version */
[39]   const PLUGIN_VERSION = "4.0.3";
[40]   
[41]   /** @var array */
[42]   private $c;
[43]   
[44]   /**

Backtrace:
#0 (): pocketmine\Server->crashDump(boolean)

GenisysPro version: 0000000000000000000000000000000000000000 [Protocol 113; API 3.0.1]
uname -a: Linux localhost 3.10.49-6733392 #1 SMP PREEMPT Wed Mar 29 20:12:38 KST 2017 armv7l
PHP version: 7.0.3
Zend version: 3.0.0
OS : Linux, android

Server uptime: 2 seconds
Number of loaded worlds: 0
Players online: 0/20

Loaded plugins:
ManyWorlds 2.0.3 by aliuly for API(s) 2.0.0
EconomyAPI 2.0.9 by onebone for API(s) 2.0.0
Fireworks_JJBH 1.0 by Jaciel by Jaciel14 for API(s) 1.12.0
PurePerms 1.3.5 by 64FF00 for API(s) 1.13.0, 2.0.0
DevToolsByMRJAYEDIT MRJAYEDIT by PocketMine Team for API(s) 3.0.0-ALPHA1
JoinTitle 1 by Kotov EditBy ThaiEdit for API(s) 3.0.0
BlockParticle 1 by FreeGamingHere for API(s) 2.0.0, 3.0.0
AddonThaiEditBar 1 by Mishka for API(s) 2.0.0, 3.0.1, 3.0.0-ALPHA2, 3.0.0-ALPHA3, 3.0.0-ALPHA4, 3.0.0-ALPHA5
ThaiEditBar 2 by ThaiEdit for API(s) 1.0.0, 2.0.0, 2.1.0, 3.0.0, 3.0.0-ALPHA1, 3.0.0-ALPHA2
SplatCraft 1.1.1 by  for API(s) 1.11.0
WorldEdit+ 0.01 by  for API(s) 2.0.0
WorldFixer 1 by CreeperFace for API(s) 1.12.0
SoupFFA 1.5.0 by McpeBooster for API(s) 3.0.0-ALPHA5, 2.0.0, 1.12.0
ClearLagg 1.1.0 by LegendOfMCPE for API(s) 3.0.0-ALPHA1
EconomyJob 2.0.4 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1, 3.0.1, 3.0.0-ALPHA3, 3.0.0-ALPHA5, 3.0.0-ALPHA7, 3.0.0-ALPHA6
```

**Comment by kenygamer** [comment]
@mote166 This repository is no longer maintained.
Please submit in the new repository.

**Comment by kenygamer** [comment]
@mote166 The new repository is [here](https://github.com/kenygamer/iProtector-v4.0). Head over to there for installing iProtector-v4.0.
