### ISSUE TITLE
The plugin don't work for me.

### ISSUE THREAD

**Issue by Meptinity** [kenygamer/iProtector-v4.0#5]
hey. could you help me? I need the plugin because I want to protect my item frame images from players. Here is the problem: I have converted the plugin to a phar file, however, my server does not start. Please convert the file to a phar or try to fix it. Thank you in advance!

Server
GenisysPRO
API 3.0.1
PHP 7.0.3

**Comment by kenygamer** [comment]
@Meptinity hello, the new repository for downloading iProtector-v4.0 is available [here](https://github.com/kenygamer/pmmp-plugins). Please submit your issue again on there.
